modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GNU LGPLv3"

[[mods]]
modId = "snailmail"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
Send mail to your friends, snail style.
'''
#logoFile = ""

[[dependencies.snailmail]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.snailmail]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.snailmail]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"