# Mod Attributes
    mod_version = 1.1.0
    mod_id = snailmail
    maven_group = dev.itsmeow.snailmail

# Forge
    mc_version = 1.20.1
    forge_version = 47.4.4
    architectury_version = 9.2.14
    fabric_loader_version = 0.16.14
    fabric_api_version = 0.92.6+1.20.1
    jvm_version = 21

# Publishing
    github = itsmeow/SnailMail
    name = SnailMail
    url = https://github.com/itsmeowCommissions/SnailMail
    curse_title = SnailMail
    curse_project_id = 396710
    curse_versions_fabric = Minecraft 1.20:1.20.1,Fabric
    curse_versions_forge = Minecraft 1.20:1.20.1,Forge
    curse_relations_fabric = fabric-api:requiredDependency,architectury-api:requiredDependency,cloth-config:optionalDependency,modmenu:optionalDependency
    curse_relations_forge = architectury-api:requiredDependency

# Toolchain Versions
    loom_version = 1.10-SNAPSHOT
    architectury_plugin_version = 3.4-SNAPSHOT

# Misc
    org.gradle.jvmargs=-Xmx6G
    org.gradle.daemon=true